force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to create log records for any unhandled exception or error.</description>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>ErrorLog-{0000}</displayFormat>
        <label>ErrorLog</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLogHelper.cls
public without sharing class ErrorLogHelper {
    
    public static void createErrorLog(String className, String methodName, String errorType, String errorMessage,
                                      String errorStackTrace)
    {
        ErrorLog__c newErrorLog = new ErrorLog__c();
        newErrorLog.ClassName__c = className;
        newErrorLog.MethodName__c = methodName;        
        newErrorLog.ErrorType__c = errorType;
        newErrorLog.ErrorMessage__c = errorMessage;
        newErrorLog.StackTrace__c = errorStackTrace;
        insert newErrorLog;
    }
    
}