force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to create log records for any unhandled exception or error.</description>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>ErrorLog-{0000}</displayFormat>
        <label>ErrorLog</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLogHelperTest.cls
@isTest
public class ErrorLogHelperTest {

    @isTest
    static void testCreateErrorLog() {
        // test variables
        String className = 'MyClass';
        String methodName = 'myMethod';
        String errorType = 'Exception';
        String errorMessage = 'An unexpected error occurred.';
        String errorStackTrace = 'SomeStackTraceHere';

        Test.startTest();
        ErrorLogHelper.createErrorLog(className, methodName, errorType, errorMessage, errorStackTrace);
        Test.stopTest();

        ErrorLog__c log = [SELECT ClassName__c, MethodName__c, ErrorType__c, ErrorMessage__c, StackTrace__c 
                           FROM ErrorLog__c ];
        
        System.assertNotEquals(null, log, 'ErrorLog__c record should be inserted.');
        System.assertEquals(className, log.ClassName__c, 'ClassName__c should match.');
        System.assertEquals(methodName, log.MethodName__c, 'MethodName__c should match.');
        System.assertEquals(errorType, log.ErrorType__c, 'ErrorType__c should match.');
        System.assertEquals(errorMessage, log.ErrorMessage__c, 'ErrorMessage__c should match.');
        System.assertEquals(errorStackTrace, log.StackTrace__c, 'StackTrace__c should match.');
    }
}