force-app/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Represent the account status, displayed on a Business AND Partner Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
                <default>true</default>
                <label>Target</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Inactive customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessReviewSegment__c.field-meta.xml
<CustomField>
    <fullName>BusinessReviewSegment__c</fullName>
    <description>Field to track the Annual Business Segmentation review. 
Only editable by specific personas</description>
    <label>Business Review Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountSegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RootAccount__c.field-meta.xml
<CustomField>
    <fullName>RootAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Root Parent)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccount</fullName>
    <active>true</active>
    <description>Represents CS Direct customers and /or End customers</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <description>Represents the Partners</description>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/BillToAccount__c.field-meta.xml
<CustomField>
    <fullName>BillToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to link to contract to the account</description>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ContractSignedDate__c.field-meta.xml
<CustomField>
    <fullName>ContractSignedDate__c</fullName>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/WorkdayReferenceId__c.field-meta.xml
<CustomField>
    <fullName>WorkdayReferenceId__c</fullName>
    <label>Workday Reference ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractShipToAccount__c/ContractShipToAccount__c.object-meta.xml
<CustomObject>
    <label>Contract Ship-to Account</label>
    <nameField>
        <displayFormat>ContractShipTo-{0000}</displayFormat>
        <label>Contract Ship-to Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Ship-to Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractShipToAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Ship-to account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract ship-to accounts</relationshipLabel>
    <relationshipName>ContractShipToAccounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractShipToAccount__c/fields/BillToAccount__c.field-meta.xml
<CustomField>
    <fullName>BillToAccount__c</fullName>
    <description>This field is populated using the before insert trigger.</description>
    <formula>Contract__r.BillToAccount__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill-to account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractShipToAccount__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract ship-to accounts</relationshipLabel>
    <relationshipName>ContractShipToAccounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractShipToAccount__c/fields/ContractSignedDate__c.field-meta.xml
<CustomField>
    <fullName>ContractSignedDate__c</fullName>
    <formula>Contract__r.ContractSignedDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OppPrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>OppPrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity main contact</description>
    <inlineHelpText>Indicate primary contact when opp is created.</inlineHelpText>
    <label>Opp primary contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/AccountSegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Mid market</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <description>CS account segmentation</description>
    <masterLabel>AccountSegment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdditionalContractSharingControllerTest.cls
@isTest
public class AdditionalContractSharingControllerTest {
    
    private static Map<String,Id> accRececTypeNameVsId = new Map<String,Id>();
    static{
        for(RecordType eachAccRecType : [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account']){
            accRececTypeNameVsId.put(eachAccRecType.DeveloperName, eachAccRecType.Id);
        }
    }
    
    @testSetup
    static void setupData(){
        
        // Create test Accounts.
        Account ultimateAcc = new Account(Name = 'Ultimate Account',
                                          RecordTypeId = accRececTypeNameVsId.get(Label.UltimateAccountRecordType));
        insert ultimateAcc;
        
        List<Account> accsToInsert = new List<Account>();
        
        Account businessAccount = new Account(Name = 'Business Account', ParentId = ultimateAcc.Id,
                                              RecordTypeId = accRececTypeNameVsId.get(Label.BusinessAccountRecordType),
                                              BusinessReviewSegment__c = Label.Enterprise,
                                              BillingCountry = 'Canada', BillingCountryCode = 'CA');
        insert businessAccount;
        
        Account partnerAccount = new Account(Name = 'Partner Account', ParentId = businessAccount.Id,
                                             BusinessReviewSegment__c = Label.MidMarket,
                                             RecordTypeId = accRececTypeNameVsId.get(Label.PartnerAccountRecordType),
                                             BillingCountry = 'India', BillingCountryCode = 'IN');
        
        Account partnerAccount1 = new Account(Name = 'Partner Account1', BusinessReviewSegment__c = Label.Enterprise,
                                              RecordTypeId = accRececTypeNameVsId.get(Label.PartnerAccountRecordType),
                                              BillingCountry = 'India', BillingCountryCode = 'IN');
        accsToInsert.add(partnerAccount);
        accsToInsert.add(partnerAccount1);
        insert accsToInsert;
    }
    
    @isTest
    static void testGetAccountToDisplay() {
        // Retrieve root account and bill to account
        Account rootAccount = [SELECT Id FROM Account WHERE Name = 'Ultimate Account' LIMIT 1];
        Account billToAccount = [SELECT Id FROM Account WHERE Name = 'Business Account' LIMIT 1];
        Account partnerAccount = [SELECT Id FROM Account WHERE Name = 'Partner Account' LIMIT 1];
        List<Account> accs = [SELECT Name FROM Account WHERE RootAccount__c = :rootAccount.Id];
        // Test getAccountToDisplay method
        List<String> accIdsToExclude = new List<String>{};
        List<AdditionalContractSharingController.AccountWrapper> accsToDisplay;
        Test.startTest();
        accsToDisplay = AdditionalContractSharingController.getAccountToDisplay(rootAccount.Id,Label.BusinessAccountRecordType,
                                                                                billToAccount.Id,accIdsToExclude);
        Test.stopTest();
        
        System.assertEquals(1, accsToDisplay.size());
        accIdsToExclude = new List<String>{};
        accsToDisplay = AdditionalContractSharingController.getAccountToDisplay(rootAccount.Id,Label.PartnerAccountRecordType,
                                                                                partnerAccount.Id,accIdsToExclude);
        
        System.assertEquals(2, accsToDisplay.size());
                accIdsToExclude = new List<String>{};
        accsToDisplay = AdditionalContractSharingController.getAccountToDisplay(null,Label.PartnerAccountRecordType,
                                                                                partnerAccount.Id,accIdsToExclude);
        
        System.assertEquals(2, accsToDisplay.size());
    }
    
    @isTest
    static void testCreateContractForAdditionalAccounts() {
        // Retrieve customer account
        Account businessAccount = [SELECT Id, AccountStatus__c FROM Account WHERE Name = 'Business Account' LIMIT 1];
        Account partnerAccount = [SELECT Id, AccountStatus__c FROM Account WHERE Name = 'Partner Account' LIMIT 1];
        Contact testContact = new Contact(LastName = 'TestConName', AccountId = businessAccount.Id);
        insert testContact;
        Opportunity testOpp = new Opportunity(AccountId = businessAccount.Id, OppPrimaryContact__c = testContact.Id, CloseDate = System.today(), 
                                              Name = 'Test Opp', StageName = '2- Sales Accepted');
        insert testOpp;
        
        Contract__c contract = new Contract__c(Name = 'Test Contract', BillToAccount__c = businessAccount.Id,
                                               ContractSignedDate__c = System.today(), WorkdayReferenceId__c = testOpp.Id);
        insert contract;
        
        // Create a List of AccountWrapper JSON
        List<AdditionalContractSharingController.AccountWrapper> accountWrapperList = new List<AdditionalContractSharingController.AccountWrapper>();
        
        AdditionalContractSharingController.AccountWrapper accWrapper = new AdditionalContractSharingController.AccountWrapper();
        accWrapper.accId = partnerAccount.Id;
        accWrapper.accStatus = 'Target';
        accountWrapperList.add(accWrapper);
        
        String jsonAccountWrapper = JSON.serialize(accountWrapperList);
        
        // Prepare parameters for createContractForAdditionalAccounts method
        List<String> parameters = new List<String>{jsonAccountWrapper, contract.Id};
        List<List<String>> flowParameters = new List<List<String>>{parameters};
        
        // Call the createContractForAdditionalAccounts method
        Test.startTest();
        AdditionalContractSharingController.createContractForAdditionalAccounts(flowParameters);
        Test.stopTest();
        
        // Verify the ContractShipToAccount__c was created
        List<ContractShipToAccount__c> contractSharings = [SELECT Id FROM ContractShipToAccount__c WHERE Account__c = :partnerAccount.Id];
        System.assertEquals(1, contractSharings.size());
        
        // Verify the Account status was updated
        partnerAccount = [SELECT Id, AccountStatus__c FROM Account WHERE Id = :partnerAccount.Id];
        System.assertEquals('Customer', partnerAccount.AccountStatus__c);
    }
}