force-app/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Represent the account status, displayed on a Business AND Partner Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
                <default>true</default>
                <label>Target</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Inactive customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessReviewSegment__c.field-meta.xml
<CustomField>
    <fullName>BusinessReviewSegment__c</fullName>
    <description>Field to track the Annual Business Segmentation review. 
Only editable by specific personas</description>
    <label>Business Review Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountSegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>Domain of the account</description>
    <label>Domain</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Calculated by the system based on the Billing Address of the Account</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RootAccount__c.field-meta.xml
<CustomField>
    <fullName>RootAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Root Parent)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractShipToAccount__c/ContractShipToAccount__c.object-meta.xml
<CustomObject>
    <label>Contract Ship-to Account</label>
    <nameField>
        <displayFormat>ContractShipTo-{0000}</displayFormat>
        <label>Contract Ship-to Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Ship-to Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractShipToAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Ship-to account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract ship-to accounts</relationshipLabel>
    <relationshipName>ContractShipToAccounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractShipToAccount__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract ship-to accounts</relationshipLabel>
    <relationshipName>ContractShipToAccounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/AccountSegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Mid market</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <description>CS account segmentation</description>
    <masterLabel>AccountSegment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APJ ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>APJ ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>APJ Japan</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA UK</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA Central</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA North</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA South</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA MENAT</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAS West</fullName>
    </customValue>
    <description>Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdditionalContractSharingController.cls
public class AdditionalContractSharingController{
    
    private static final String CLASS_NAME = AdditionalContractSharingController.class.getName();
    private static List<String> accStatuses = new List<String>{Constants.TARGET, Constants.PROSPECT, Constants.INACTIVATED_CUSTOMER};

        @AuraEnabled
        public static List<AccountWrapper> getAccountToDisplay(String rootAccId, String recordTypeDeveloperName, String billToAccId, List<String> accIdsToExclude){
            List<Account> accsToDisplay;
            List<AccountWrapper> accWrapperList = new List<AccountWrapper>();
            try{
                if(String.isBlank(rootAccId)){
                    rootAccId = billToAccId; //set Root Account Id in case the bill to account is the root account.
                }
                accIdsToExclude.add(billToAccId);               
                if(Label.BusinessAccountRecordType.equalsIgnoreCase(recordTypeDeveloperName)){
                    accsToDisplay = [SELECT Name, RecordType.DeveloperName, AccountStatus__c, Domain__c, BusinessReviewSegment__c,
                                     BillingCountry, Region__c
                                     FROM Account 
                                     WHERE Id NOT IN: accIdsToExclude 
                                     AND RecordType.DeveloperName != :Label.UltimateAccountRecordType
                                     AND (RootAccount__c = :rootAccId OR Id = :rootAccId) WITH USER_MODE];
                }
                else if(Label.PartnerAccountRecordType.equalsIgnoreCase(recordTypeDeveloperName)){
                    accsToDisplay = [SELECT Name, RecordType.DeveloperName, AccountStatus__c, Domain__c, BusinessReviewSegment__c,
                                     BillingCountry, Region__c
                                     FROM Account
                                     WHERE Id NOT IN: accIdsToExclude 
                                     AND RecordType.DeveloperName != :Label.UltimateAccountRecordType WITH USER_MODE];
                }
                for(Account eachAccount : accsToDisplay){
                    AccountWrapper newAccWrapper = new AccountWrapper();
                    newAccWrapper.accId = eachAccount.Id;
                    newAccWrapper.accName = eachAccount.Name;
                    newAccWrapper.accRecordType = eachAccount.RecordType.DeveloperName;
                    newAccWrapper.accStatus = eachAccount.AccountStatus__c;
                    newAccWrapper.accDomain = eachAccount.Domain__c;
                    newAccWrapper.accBusinessReviewSegment = eachAccount.BusinessReviewSegment__c;
                    newAccWrapper.accCountry = eachAccount.BillingCountry;
                    newAccWrapper.accRegion = eachAccount.Region__c;
                    accWrapperList.add(newAccWrapper);
                }
                return accWrapperList;
            }
            catch(Exception ex){
                ErrorLogHelper.createErrorLog(CLASS_NAME, 'getAccountToDisplay', ex.getTypeName(), ex.getMessage(), ex.getStackTraceString());
                return accWrapperList;
            }        
        }
    
    @InvocableMethod
    public static void createContractForAdditionalAccounts(List<List<String>> flowParameter){        
        try{
            List<Account> accsToUpdate = new List<Account>();
            List<String> originalParametersPassed = flowParameter[0];
            String selectedAccRecords = originalParametersPassed[0];
            String contractId = originalParametersPassed[1];
            List<AccountWrapper> listOfAccountWrapper = (List<AccountWrapper>) JSON.deserialize(selectedAccRecords, List<AccountWrapper>.class);
            List<ContractShipToAccount__c> contractSharings = new List<ContractShipToAccount__c>();
            for(AccountWrapper eachAccWrapper : listOfAccountWrapper){
                contractSharings.add(new ContractShipToAccount__c(Account__c = eachAccWrapper.accId , Contract__c = contractId));
                if(accStatuses.contains(eachAccWrapper.accStatus)){
                    accsToUpdate.add(new Account(Id = eachAccWrapper.accId, AccountStatus__c = Constants.CUSTOMER));
                }
            }
            insert contractSharings;
            if(!accsToUpdate.isEmpty()){
               update accsToUpdate;
            } 
        }
        catch(Exception ex){
            ErrorLogHelper.createErrorLog(CLASS_NAME, 'createContractForAdditionalAccounts', ex.getTypeName(), ex.getMessage(), ex.getStackTraceString());
        }        
    }
    
    public Class AccountWrapper{
        @AuraEnabled public String accId;
        @AuraEnabled public String accName;
        @AuraEnabled public String accRecordType;
        @AuraEnabled public String accStatus;
        @AuraEnabled public String accDomain;
        @AuraEnabled public String accBusinessReviewSegment;
        @AuraEnabled public String accCountry;
        @AuraEnabled public String accRegion;
    }
}